const DEFAULTCOLS = 24;

const CONTAINERCONFIG = {
  DEFAULTCOLS: 24,
  DEFAULTROWHEIGHT: 12,
  DEFAULTMARGIN: 15,
  DEFAULTHEIGHT: 20,
  DEFAULTWIDTH: DEFAULTCOLS / 2,
};

export default CONTAINERCONFIG;
