import lineDefualtConfing from '@/constants/line/config';
import pieDefualtConfing from '@/constants/pie/config';
import testing from '@/constants/dashboardConfig/testing';

const height = 350;

const all = [
  {
    id: 'chinMap',
    text: '中国地图',
    api: 'getMapData',
    curType: 'map',
  },
  {
    id: 'nu',
    text: '新增用户',
    api: 'userNu',
    hasParams: true,
    curType: 'card',
  },
  {
    id: 'overall',
    text: '累计用户',
    api: 'overall',
    hasParams: true,
    curType: 'card',
  },
  {
    id: 'userUa',
    text: '活跃用户',
    api: 'userUa',
    hasParams: true,
    curType: 'card',
  },
  {
    id: 'uatTrend',
    text: '活跃用户走势',
    subtext: '活跃用户的走势图',
    align: 'center',
    api: 'uatTrend',
    hasParams: true,
    curType: 'line',
    ...lineDefualtConfing,
    span: 12,
    height,
  },
  {
    id: 'nuTrend',
    text: '新增用户走势',
    subtext: '新增用户的走势图',
    align: 'center',
    api: 'nuTrend',
    hasParams: true,
    curType: 'line',
    span: 12,
    height,
    ...lineDefualtConfing,
  },
  {
    id: 'overallTrend',
    text: '累计用户增长趋势',
    subtext: '累计用户增长趋势的图',
    align: 'center',
    api: 'overallTrend',
    hasParams: true,
    curType: 'line',
    span: 12,
    height,
    ...lineDefualtConfing,
  },
  {
    id: 'pv',
    text: '页面访问次数',
    subtext: '页面访问次数的走势图',
    align: 'center',
    api: 'pv',
    hasParams: true,
    curType: 'line',
    span: 12,
    height,
    ...lineDefualtConfing,
  },
  {
    id: 'browserType',
    text: '浏览器类型分布',
    subtext: '浏览器类型分布的图',
    align: 'center',
    api: 'browserType',
    hasParams: false,
    curType: 'pie',
    linkTo: 'browserDashboard',
    apiKeys: 'browserName',
    span: 12,
    height,
    ...pieDefualtConfing,
  },
  {
    id: 'osType',
    text: '系统类型分布',
    subtext: '系统类型分布的图',
    align: 'center',
    api: 'osType',
    hasParams: false,
    curType: 'pie',
    linkTo: 'osDashboard',
    apiKeys: 'osName',
    span: 12,
    height,
    ...pieDefualtConfing,
  },
  {
    id: 'rankByUser',
    text: '页面浏览排名（按访问用户数）',
    subtext: '页面浏览排名（按访问用户数）的走势图',
    align: 'center',
    api: 'rankByUser',
    hasParams: true,
    curType: 'pie',
    span: 12,
    height: 600,
    ...pieDefualtConfing,
  },
  {
    id: 'rankByView',
    text: '页面浏览排名（按访问量）',
    subtext: '页面浏览排名（按访问量）的走势图',
    align: 'center',
    api: 'rankByView',
    hasParams: true,
    curType: 'pie',
    span: 12,
    height: 600,
    ...pieDefualtConfing,
  },
  {
    id: 'retention',
    text: '用户留存分析',
    align: 'center',
    api: 'retention',
    hasParams: true,
    curType: 'table',
    needFormat: true,
    clickOpen: true,
    linkTo: 'retentionUserListDashboard',
    apiKeys: 'firstTime,retentionTime',
    tableSource: {
      row: 'first_time',
      col: 'title',
    },
  },
  ...testing,
];

export default all;
