const height = 450;

const page2 = [
  {
    id: 'uvSummary',
    title: '访问用户',
    api: 'uvSummary',
    hasParams: true,
    markPoint: false,
    markLine: 'off',
    span: 4,
    help: '指定时间活跃（即访问）的用户数',
    chart: {
      curType: 'bar',
      height: 60,
      unit: '人',
      yAxis: {
        show: false,
      },
    },
    curType: 'card1',
    buttonText: '最大活跃数',
  },
  {
    id: 'utSummary',
    title: '租户数',
    api: 'utSummary',
    hasParams: true,
    markPoint: false,
    markLine: 'off',
    span: 4,
    curType: 'card1',
    help: '累计注册的租户总数',
    chart: {
      curType: 'bar',
      height: 60,
      unit: '人',
      yAxis: {
        show: false,
      },
    },
    buttonText: '最大活跃数',
    // mock: {
    //     code: 'U000000',
    //     data: {
    //         total: '6,560',
    //     },
    //   },
  },
  {
    id: 'orgUaSummary',
    title: '机构数',
    api: 'orgUaSummary',
    hasParams: true,
    span: 4,
    offsetSpan: 12,
    help: '指定时间活跃（即访问）的机构数',
    curType: 'card1',
    markPoint: false,
    markLine: 'off',
    chart: {
      curType: 'bar',
      height: 60,
      unit: '人',
      yAxis: {
        show: false,
      },
    },
    buttonText: '最大活跃数',
    // mock: {
    //     code: 'U000000',
    //     data: {
    //         total: '6,560',
    //     },
    //   },
  },
  // {
  //   id: 'userNum',
  //   title: '用户数',
  //   api: 'userNum',
  //   hasParams: true,
  //   span: 4,
  //   offsetSpan: 4,
  //   curType: 'card1',
  //   mock: {
  //       code: 'U000000',
  //       data: {
  //           total: '6,560',
  //       },
  //     },
  // },
  {
    id: 'userOverAllTrend',
    title: '累计用户增长走势',
    align: 'center',
    api: 'userOverAllTrend',
    unit: '人',
    help: '指定时间内新增（即注册）的用户数变化',
    markLine: 'off',
    hasParams: true,
    curType: 'line',
    span: 12,
    height,
    xAxis: {
      type: 'category',
    },
  },
  {
    id: 'loginCntTrend',
    title: '用户登录活跃走势',
    align: 'center',
    help: '指定时间内用户的登录应用次数变化',
    api: 'loginCntTrend',
    hasParams: true,
    curType: 'line',
    span: 12,
    height,
    unit: '次',
  },
  {
    id: 'uaByApp',
    title: '应用活跃分布',
    help: '指定时间各应用活跃（即访问）的用户数分布',
    align: 'center',
    api: 'uaByApp',
    hasParams: true,
    curType: 'pie',
    span: 12,
    radius: ['40%', '60%'],
    label: {
      fontSize: 14,
    },
    height,
  },
  {
    id: 'browserType',
    title: '浏览器类型分布',
    align: 'center',
    help: '指定时间内活跃（即访问）的浏览器，访问的用户人数',
    api: 'browserType',
    hasParams: true,
    curType: 'pie',
    linkTo: 'browserDashboard',
    apiKeys: 'browserName',
    span: 12,
    height,
  },
  {
    id: 'osType',
    title: '操作系统类型分布',
    align: 'center',
    help: '指定时间内活跃（即访问）的操作系统，访问的用户人数',
    api: 'osType',
    hasParams: true,
    curType: 'pie',
    linkTo: 'osDashboard',
    apiKeys: 'osName',
    span: 12,
    height,
  },
];

export default page2;
